#!/bin/bash
array=()
while IFS=  read -r -d $'\0'; do
    array+=("$REPLY")
done < <(find ~/dokumente ~/studium -type f -iname "*$1*$2*$3*" -print0)
for i in "${!array[@]}"; do 
  printf "%s\t%s\n" "$i" "${array[$i]}"
done
#printf '%s\n' "${array[@]}"
echo "select index of file to open"
read index
fileToOpen="${array[$index]}"
libreoffice "$fileToOpen" &
