#!/usr/bin/python
import sys
import subprocess
from lib import findEngine

#terminal edit or normal edit?
terminalEdit=False;
lastArg = sys.argv[len(sys.argv)-1];
if lastArg == "term":
    print("terminal edit acitvated")
    terminalEdit=True;

amountArgs = len(sys.argv)-1;
if terminalEdit:
    amountArgs=amountArgs-1;
print("amount Searchwords: %d" % amountArgs);

searchWords=[];
for i in range(amountArgs):
    searchWord =sys.argv[i+1]
    print("search word: %s" % searchWord);
    searchWords.append(searchWord);



selected = findEngine.findAndSelect(searchWords);
print("selected: %s" % selected);

if terminalEdit is True:
    subprocess.Popen("vim \"%s\"" % selected,shell=True)
else:
    subprocess.Popen("gedit \"%s\"" % selected,shell=True)




