#!/usr/bin/python


# what:
# gloabally finds files, let user choose one and open in editor
# how:
# findAndEdit searchWords... [term]
# searchWords must be contained in filename in the given order,
# but there may be other character before and after each search word
# if last arg is "term", than vim is used instead of gedit to open file
# all matching files are presented with index and user can choose word by index.
# if only one file is found, it is opened without user questioning.
# dependencies:
# lib/findEngine.py
# vim, gedit

import sys
import subprocess
from lib import findEngine


p = subprocess.Popen("printenv CPV_DOC_DIR",shell=True,stdout=subprocess.PIPE)
docDir, err = p.communicate()

if not docDir or len(docDir) is 0:
    print("No Doc dir found, falling back to root dir: /");
    docDir="/";

amountArgs = len(sys.argv)-1;
print("amount Searchwords: %d" % amountArgs);

searchWords=[];
for i in range(amountArgs):
    searchWord =sys.argv[i+1]
    print("search word: %s" % searchWord);
    searchWords.append(searchWord);

selected = findEngine.findAndSelect(searchWords,dir=docDir);
print("selected: %s" % selected);


subprocess.Popen("libreoffice \"%s\"" % selected,shell=True)

