#!/usr/bin/python
from lib import findEngine
import subprocess
import sys

amountArgs = len(sys.argv)-1;
searchWords=[];
for i in range(amountArgs):
    searchWord =sys.argv[i+1]
    print("search word: %s" % searchWord);
    searchWords.append(searchWord);


selected = findEngine.findAndSelect(searchWords,file=False);
subprocess.Popen("cd \"%s\"" % selected,shell=True)
