#!/bin/sh
# was:
# interaktiv packen oder entpacken von tar.gz archiven
# wie
# tgz
# man wird interaktiv durch den prozess geführt, alles findet im aktuellen working dir statt
read -p "p = packen, e = entpacken" packen
if [ "$packen" = "p" ]
	then
	read -p "Bitte archivName angeben" archiv
	tar cfvz $archiv $1
elif [ "$packen" = "e" ]
	then
	tar -xzf $1
else
	echo du musst p oder e eingeben - beenden 
fi

